# Generated by Django 2.0.3 on 2018-03-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Glosowanie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uchwala',
            options={'verbose_name': 'Uchwala', 'verbose_name_plural': 'Uchwały'},
        ),
    ]
