# Generated by Django 2.0.3 on 2018-03-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Glosowanie', '0002_auto_20180318_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosowanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('Za', 'Za'), ('Przeciw', 'Przeciw'), ('Wstrzymuję się', 'Wstrzymuję się')], max_length=20)),
                ('id_uchwaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Glosowanie.Uchwala')),
            ],
        ),
    ]
