# Generated by Django 2.0.3 on 2018-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uzytkownicy', '0003_remove_uzytkowik_id_glosowania'),
        ('Glosowanie', '0003_glosowanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosowanie',
            name='id_uzytkownika',
            field=models.ManyToManyField(to='Uzytkownicy.Uzytkowik'),
        ),
    ]
