# Generated by Django 2.0.3 on 2018-03-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uzytkownicy', '0003_remove_uzytkowik_id_glosowania'),
        ('Glosowanie', '0004_glosowanie_id_uzytkownika'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosowanie',
            name='id_uzytkownika',
        ),
        migrations.AddField(
            model_name='glosowanie',
            name='id_uzytkownika',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Uzytkownicy.Uzytkowik'),
        ),
    ]
