# Generated by Django 2.0.3 on 2018-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glosowanie', '0008_auto_20180318_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosowanie',
            name='vote',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Za'), (0, 'Przeciw'), (2, 'Wstrzymuję się')], default=None),
        ),
    ]
