# Generated by Django 2.0.3 on 2018-03-26 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Glosowanie', '0009_auto_20180320_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchwala',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
