# Generated by Django 2.0.3 on 2018-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glosowanie', '0010_uchwala_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uchwala',
            name='date_add',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
