# Generated by Django 2.0.3 on 2018-03-26 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glosowanie', '0011_auto_20180326_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uchwala',
            name='date_add',
            field=models.DateField(default=datetime.date.today, verbose_name='Data dodania'),
        ),
    ]
