# Generated by Django 2.0.3 on 2018-04-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glosowanie', '0012_auto_20180326_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uchwala',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tytuł uchwały'),
        ),
    ]
