# Generated by Django 2.0.3 on 2018-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glosowanie', '0003_glosowanie'),
        ('Uzytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkowik',
            name='id_glosowania',
        ),
        migrations.AddField(
            model_name='uzytkowik',
            name='id_glosowania',
            field=models.ManyToManyField(to='Glosowanie.Glosowanie'),
        ),
    ]
