# Generated by Django 2.0.3 on 2018-03-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uzytkownicy', '0002_auto_20180318_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkowik',
            name='id_glosowania',
        ),
    ]
