# Generated by Django 2.0.3 on 2018-03-20 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Uzytkownicy', '0003_remove_uzytkowik_id_glosowania'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzytkowik',
            new_name='Uzytkownik',
        ),
    ]
