# Generated by Django 2.0.3 on 2018-03-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uzytkownicy', '0004_auto_20180320_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='user',
        ),
        migrations.DeleteModel(
            name='Uzytkownik',
        ),
    ]
